[CCgenerator]
output-dir = .
max-line-width = 33
max-line-count = 3
; all, srt, csv, txt
output-format = all
; default, cpu, cuda ; default = if torch detected defaults to cuda otherwise cpu
device = default
device-index = 0
batch-size = 8
threads = 0
; "default", "float16", "float32", "int8"
compute-type = int8
low-resources = false
print-progress = false
verbose = false
log-level = None
secrets = .secrets

[whisperX]
; Model list from faster_whisper.utils
;    "tiny.en": "Systran/faster-whisper-tiny.en"
;    "tiny": "Systran/faster-whisper-tiny"
;    "base.en": "Systran/faster-whisper-base.en"
;    "base": "Systran/faster-whisper-base"
;    "small.en": "Systran/faster-whisper-small.en"
;    "small": "Systran/faster-whisper-small"
;    "medium.en": "Systran/faster-whisper-medium.en"
;    "medium": "Systran/faster-whisper-medium"
;    "large-v1": "Systran/faster-whisper-large-v1"
;    "large-v2": "Systran/faster-whisper-large-v2"
;    "large-v3": "Systran/faster-whisper-large-v3"
;    "large": "Systran/faster-whisper-large-v3"
;    "distil-large-v2": "Systran/faster-distil-whisper-large-v2"
;    "distil-medium.en": "Systran/faster-distil-whisper-medium.en"
;    "distil-small.en": "Systran/faster-distil-whisper-small.en"
;    "distil-large-v3": "Systran/faster-distil-whisper-large-v3"
;    "distil-large-v3.5": "distil-whisper/distil-large-v3.5-ct2"
;    "large-v3-turbo": "mobiuslabsgmbh/faster-whisper-large-v3-turbo"
;    "turbo": "mobiuslabsgmbh/faster-whisper-large-v3-turbo"
whisperx-model = turbo
whisperx-model-cache-only = true
whisperx-model-dir = ~/.cache/whisperx
whisperx-align-model-cache-only = true
whisperx-align-model-dir = ~/.cache/whisperx
highlight-words = False

[PyAnnote]
; community, precision
; Note precision is paid for and requires a pyannote key in .secrets
pyannote-model = community
pyannote-model-dir = ~/.cache/pyannote

[ASP]
; default is MIT audioforge-ast-fsd50k
asp-model = fsd50k
asp-model-cache-only = true
asp-model-dir = ~/.cache/asp
score-threshold = 0.1
